# Generated by Django 5.1.2 on 2024-12-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobileno',
            new_name='mobno',
        ),
    ]
